import type { StoryData } from '../../types.js';
import { escapeHtml } from '../../utils/stats.js';

export function generateEpilogue(data: StoryData): string {
  const repoName = escapeHtml(data.repoName);
  const timespan = formatTimespanMonths(data.firstCommitDate, data.lastCommitDate);
  const additions = data.totalAdditions.toLocaleString('en-US');
  const deletions = data.totalDeletions.toLocaleString('en-US');

  return `
  <section id="epilogue" class="fade-in">
    <div class="epilogue-content">
      <h2 class="gradient-text">The Story So Far</h2>
      <p class="epilogue-trajectory">From the first commit to the last, <strong>${repoName}</strong> spans ${timespan} with ${data.totalContributors} contributors.</p>
      <div class="epilogue-stats">
        <div class="epilogue-stat">
          <span class="epilogue-stat-value">${data.totalCommits}</span>
          <span class="epilogue-stat-label">Commits</span>
        </div>
        <div class="epilogue-stat">
          <span class="epilogue-stat-value">${data.totalContributors}</span>
          <span class="epilogue-stat-label">Contributors</span>
        </div>
        <div class="epilogue-stat">
          <span class="epilogue-stat-value">${additions}</span>
          <span class="epilogue-stat-label">Lines Added</span>
        </div>
        <div class="epilogue-stat">
          <span class="epilogue-stat-value">${deletions}</span>
          <span class="epilogue-stat-label">Lines Removed</span>
        </div>
        <div class="epilogue-stat">
          <span class="epilogue-stat-value">${timespan}</span>
          <span class="epilogue-stat-label">Timespan</span>
        </div>
      </div>
      <div class="epilogue-badge">Generated by GitStory</div>
    </div>
  </section>`;
}

function formatTimespanMonths(start: Date, end: Date): string {
  const diffMs = end.getTime() - start.getTime();
  const days = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (days < 1) return 'less than a day';
  if (days < 30) return `${days} day${days === 1 ? '' : 's'}`;

  const months = Math.round(days / 30);
  if (months < 12) return `${months} month${months === 1 ? '' : 's'}`;

  const years = Math.floor(months / 12);
  const remainingMonths = months % 12;
  if (remainingMonths === 0) return `${years} year${years === 1 ? '' : 's'}`;
  return `${years} year${years === 1 ? '' : 's'}, ${remainingMonths} month${remainingMonths === 1 ? '' : 's'}`;
}
