import { describe, it, expect } from 'vitest';
import { generateEpilogue } from '../../../report/sections/epilogue.js';
import type { StoryData } from '../../../types.js';

function makeStoryData(overrides: Partial<StoryData> = {}): StoryData {
  return {
    repoName: 'my-repo',
    title: 'My Repo',
    totalCommits: 142,
    totalContributors: 7,
    totalAdditions: 9500,
    totalDeletions: 3200,
    firstCommitDate: new Date('2023-01-15'),
    lastCommitDate: new Date('2024-06-20'),
    chapters: [],
    contributors: [],
    dailyActivity: [],
    commits: [],
    ...overrides,
  };
}

describe('generateEpilogue', () => {
  it('returns HTML with id="epilogue"', () => {
    const html = generateEpilogue(makeStoryData());
    expect(html).toContain('id="epilogue"');
  });

  it('contains fade-in class', () => {
    const html = generateEpilogue(makeStoryData());
    expect(html).toContain('fade-in');
  });

  it('contains summary stat for commits', () => {
    const html = generateEpilogue(makeStoryData({ totalCommits: 142 }));
    expect(html).toContain('142');
  });

  it('contains summary stat for contributors', () => {
    const html = generateEpilogue(makeStoryData({ totalContributors: 7 }));
    expect(html).toContain('7');
  });

  it('contains summary stat for timespan', () => {
    const html = generateEpilogue(makeStoryData({
      firstCommitDate: new Date('2023-01-15'),
      lastCommitDate: new Date('2024-06-20'),
    }));
    // Should contain a timespan string (year + months)
    expect(html).toContain('1 year, 5 months');
  });

  it('contains lines added and removed', () => {
    const html = generateEpilogue(makeStoryData({
      totalAdditions: 9500,
      totalDeletions: 3200,
    }));
    expect(html).toContain('9,500');
    expect(html).toContain('3,200');
  });

  it('contains project trajectory text', () => {
    const html = generateEpilogue(makeStoryData());
    const lower = html.toLowerCase();
    expect(lower).toContain('first commit');
    expect(lower).toContain('contributors');
  });

  it('contains "Generated by GitStory" badge text', () => {
    const html = generateEpilogue(makeStoryData());
    expect(html).toContain('Generated by GitStory');
  });

  it('escapes HTML in repo name', () => {
    const html = generateEpilogue(makeStoryData({ repoName: '<script>alert("xss")</script>' }));
    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;');
  });
});
